### PR TITLE
	 Added new feature: slide-up transition.

### PR DESCRIPTION
**Pull request by jbeard4**
```
 Added new feature: slide-up transition, which slides the screen from bottom to top (or top to bottom, if reverse is true). This is like modal transition, except the current screen also slides out.
```

### CODE REVIEW

**Comment by ajoslin** [comment]
Hi @jbeard4 - sorry for the huge wait. Life has been crazy.  I'll check this on Saturday.

**Comment by jbeard4** [comment]
No problem. There's likely more to come.

**Comment by ajoslin** [comment]
Alright @jbeard4, finally! This looks great. I'll rebase and merge it :)

**Comment by ajoslin** [comment]
Thanks a lot! Landed in 5ba5ec49447ee01228888f687557079846937b8a

**Comment by jbeard4** [comment]
Super :)

**Pull request closed without merging**
